### ISSUE TITLE
thausends over thausends messeseges for suspicios_login

### ISSUE THREAD

**Issue by gueniewie** [nextcloud/suspicious_login#115]
I have a connection from a synologic nas over webdav to the nextcloud server both have a fixed IP (IPv4) I have level 2 and level 4 messages?

What is the way to secure this IP from external or stop the million messages ?

Thanks for a answer 
Günther

**Comment by ChristophWurst** [comment]
> I have level 2 and level 4 messages?

please elaborate

> What is the way to secure this IP from external or stop the million messages ?

use an app password

**Comment by gueniewie** [comment]
I attache a small log from 5 sec.

I don't understand this "use a app password" this is a sync from a synology NAS to nextcloud
[nextcloud.log](https://github.com/nextcloud/suspicious_login/files/3497126/nextcloud.log)

**Comment by gueniewie** [comment]
Now I have this in Configure Nextcloud??Statistiken der Trainingsdaten

Bisher hat die Anwendung 8448523 Anmeldungen (eingeschlossen Anwendungsverbindungen) erfasst, von denen 7 eindeutige (IP, UID) Tupel sind.
Statistiken des Kriterienmodells

Ein Kriterienmodell wurde bis jetzt noch nicht erstellt. Dies bedeutet, dass die Anwendung höchstwahrscheinlich erst kürzlich aktiviert wurde. Um ein Kriterienmodell erstellen zu können, wird eine verlässliche Datenbasis benötigt. Aus diesem Grund wartet die Anwendung, bis Anmeldungen von mindestens 60 Tagen erfasst wurden. 
??

**Comment by ChristophWurst** [comment]
> ??

Yes. Is there anything unclear about the explanatory text?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/suspicious_login/blob/v1.0.0/lib/Service/LoginClassifier.php <- the classifier should not send a warning if there is no model. Your report is a bit misleading thus.
