### ISSUE TITLE
Lots of warnings for IPv6 addresses on local subnet

### ISSUE THREAD

**Issue by LeSpocky** [nextcloud/suspicious_login#192]
I installed version 1.0.0 on nextcloud 16 recently and I get a lot warnings all from the same IPv6 subnet, which happens to the local subnet the server is in:

    fd5b:db8:beef:0::/64

This is rather annoying, because clients change their "interface identifier" part of their address frequently for privacy reasons.

Is there an option for whitelisting IP ranges (although this might have security implications if attackers get access to that net)?

**Comment by ChristophWurst** [comment]
Fixed by #107, but that is unfortunately only available for 17+ as we require a new API that is not available in 16.

Closing as wontfix as newer versions have a classifier for ipv6 and thus should work well when using them.
