### ISSUE TITLE
Warning	suspicious_login	Could not predict suspiciousness: No models found

### ISSUE THREAD

**Issue by Niemand112233** [nextcloud/suspicious_login#197]
Hi,

I get this error "Warning | suspicious_login | Could not predict suspiciousness: No models found" a lot. 

How to fix?

NC 17.0.1

**Comment by ChristophWurst** [comment]
> How to fix?

Increase your log level. This is just a warning. It will vanish once enough data has been gathered to train a NN model. This can take some time.

**Comment by laurentperrinet** [comment]
One suggestion would be that the app would not generate such warning every second in my case), knowing that the model is not trained without 60 days of data. What do you think?

**Comment by ChristophWurst** [comment]
Makes sense. Wanna submit a pull request to lower the log level to debug?

**Comment by ChristophWurst** [comment]
Try it ;-)

**Comment by laurentperrinet** [comment]
I tried to look at the code in https://github.com/nextcloud/suspicious_login/blob/master/lib/Service/LoginClassifier.php - but it is very remote from anything I have red in my life. (I mainly develop neural networks in pyTorch.)

**Comment by hatelamers** [comment]
why it was closed as "invalid"? I am disabling Suspisious Login altogeher because of this: it generates massive log spam and makes log access from UI impossible
please reopen, you even may get a PR then

**Comment by bublboblz** [comment]
> why it was closed as "invalid"? I am disabling Suspisious Login altogeher because of this: it generates massive log spam and makes log access from UI impossible please reopen, you even may get a PR then

Same question: why this issue was closed as invalid?
My logs were kinda flooded with these unuseful warning (as far as it's a normal situation until the model ain't trained), so I also disabled the extension.

**Comment by JRGonz** [comment]
I wound up disabling suspicious login. It should be called suspicious logging instead.

**Comment by ninjazan420** [comment]
I've got that error, too. For me it's Thunderbird, that's trying to connect to the calender.

"method": "REPORT",
  "url": "/remote.php/dav/calendars/user/inbox/",
  "message": "Could not predict suspiciousness: No models found",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Thunderbird/115.10.1",
  "version": "28.0.5.1",

>  once enough data has been gathered to train a NN model. This can take some time.

How long may this take? The warnings are up for 2 weeks now :)
28.0.5 here

**Comment by banigithub-2** [comment]
My AIO installation has been logging this every second for many months.  With only a couple of users, is it likely that a model will never be built?  Seems a little pointless.  Guess the answer is to disable the module.

**Comment by marcolaux** [comment]
> My AIO installation has been logging this every second for many months. With only a couple of users, is it likely that a model will never be built? Seems a little pointless. Guess the answer is to disable the module.

I experience the same. I needed to disable the plugin to stay sane about my logs.

**Comment by ChristophWurst** [comment]
Thank you for your feedback

**Comment by marcolaux** [comment]
Sure, the question of how to resolve this still applies.

you mentioned

> Increase your log level. This is just a warning. It will vanish once enough data has been gathered to train a NN model. This can take some time.

But how much data is enough so that my logs can be kept clean?

I don't think it's a good idea to have thousands of warning log entries within a month when there is essentially nothing to warn about.

It is not clear if this is a real error and I should look at something or not.

**Comment by ChristophWurst** [comment]
> I don't think it's a good idea to have thousands of warning log entries within a month when there is essentially nothing to warn about.

I'd say update your system. If you still see *warning* and not *debug* logs then you are running an outdated stack. The log level was lowered to https://github.com/nextcloud/suspicious_login/pull/875. I hope you are not running debug logs in production.

**Comment by marcolaux** [comment]
> I'd say update your system. If you still see _warning_ and not _debug_ logs then you are running an outdated stack. The log level was lowered to [#875](https://github.com/nextcloud/suspicious_login/pull/875). I hope you are not running debug logs in production.

it's an up to date AIO instance and I haven't enabled debug logs

**Comment by ChristophWurst** [comment]
In that case I can only assume you are not talking about the same log line as it was reported by OP.

See https://github.com/nextcloud/suspicious_login/blob/eae28c41b09bc4e61b8640422221e97d80bba5c4/lib/Service/LoginClassifier.php#L79
