### ISSUE TITLE
Integrate IP geolocation into notifications

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/suspicious_login#209]
For now, my users are rather irritated than helped by the suspicious login notifications. It would be somewhat more useful if the notification cloud integrate geolocation and say something like "we detected a new login from location XXX" than just the raw IP address, or at least provide a link to a geolocation service that resolves the IP address to a location for you.

**Comment by ChristophWurst** [comment]
> at least provide a link to a geolocation service

do you know any hosted FLOSS that does that?

**Comment by rullzer** [comment]
IMO we should have this as a service in core (and then apps that can rpovide the lookup). As this could be useful in other parts as well.

**Comment by vasyugan** [comment]
> > at least provide a link to a geolocation service
> 
> do you know any hosted FLOSS that does that?

I honestly don't know. But of geoip data is freely available, I would indeed think that @rullzer has it right and linking to an external service would be a kludge anyway.

**Comment by jookk** [comment]
Or use geoip2 server module for lookups.
It is available to nginx and apache2 too.
Maxmind database (geoip2lite) are free.
Lookups are then internal.
https://github.com/maxmind/libmaxminddb
https://github.com/leev/ngx_http_geoip2_module
https://maxmind.github.io/mod_maxminddb/index.html

**Comment by g6094199** [comment]
> > at least provide a link to a geolocation service
> 
> do you know any hosted FLOSS that does that?

DD-WRT uses Flagfox just like this:

 https://iplookup.flagfox.net/?ip=95.217.53.153

**Comment by vasyugan** [comment]
> 
> 
> > > at least provide a link to a geolocation service
> > 
> > 
> > do you know any hosted FLOSS that does that?
> 
> DD-WRT uses Flagfox just like this:
> 
> https://iplookup.flagfox.net/?ip=95.217.53.153

That would require the user to install a browser extension. That's something that very few of my users will no, almost certainly not those who innundate me with mails because they are confused about notifications received from the app. But given that  there are geoip2 modules for both Apache and NGINX, this sound like a reasonable way to go.

**Comment by g6094199** [comment]
No,
there is no need to install a plugin. It just runs out of the box on any browser.

![Bildschirmfoto vom 2021-04-19 08-19-34](https://user-images.githubusercontent.com/37833326/115190434-4a0aa300-a0e8-11eb-8b0e-1f951ff5156c.png)

**Comment by vasyugan** [comment]
> No,
> there is no need to install a plugin. It just runs out of the box on any browser.
> 
> ![Bildschirmfoto vom 2021-04-19 08-19-34](https://user-images.githubusercontent.com/37833326/115190434-4a0aa300-a0e8-11eb-8b0e-1f951ff5156c.png)

Could this be implemented in the app? I guess the effort should be small @ChristophWurst  The thing is that I still frequently get support requests from users who have no idea what to do with this.  Alternatively I could just uninstall the app, but I'd rather see it made more usable.

**Comment by ChristophWurst** [comment]
Sure, this could be implemented as optional feature.

**Comment by vasyugan** [comment]
> Sure, this could be implemented as optional feature.

I appreciate your reply, however, I don't see this as "optional" as the naked IP address isn't of much use.  I frequently receive mails by users who simply don't know what it is. (and for some reason, you can't even copy the IP address from the notification, you have to memorize it and enter it by hand in the geolocation service of your choice. ) All the services I know of that alert users in case of a suspicious login give the geolocation based approximate location. This is essential to make it useful, as the decision what to do with this piece of information is up to the user.

**Comment by metaview** [comment]
It might be enough if the email contains the url to the service linked to the ip address.

**Comment by vasyugan** [comment]
> It might be enough if the email contains the url to the service linked to the ip address.

same for the notification in Nextcloud (including in the mobile apps)

**Comment by vasyugan** [comment]
It is a particular nuisance, that even when you know what IP addresses are and how they are related to your geographical location, you cannot copy the IP address from the notification shown in the nextcloud web interface in order to paste it into the search field of a geolocation provider. You have to memorize it and type it by hand.

**Comment by ChristophWurst** [comment]
As you know this isn't a bug of the suspicious login app https://github.com/nextcloud/notifications/issues/572 :wink:

**Comment by vasyugan** [comment]
> As you know this isn't a bug of the suspicious login app [nextcloud/notifications#572](https://github.com/nextcloud/notifications/issues/572) wink

@ChristophWurst Thanks, I wasn't aware that this bug had been reassigned. But haven't I seen clickable notifications in the past?

Wouldn't it be possible for the suspicious logins app to create notifications that contains the ip address in form of a clickable URL, clicking which looks the IP address up at a geolocation website?

**Comment by szaimen** [comment]
> Wouldn't it be possible for the suspicious logins app to create notifications that contains the ip address in form of a clickable URL, clicking which looks the IP address up at a geolocation website?

This sounds like a good idea to me 👍

**Comment by ChristophWurst** [comment]
> Wouldn't it be possible for the suspicious logins app to create notifications that contains the ip address in form of a clickable URL, clicking which looks the IP address up at a geolocation website?

As, as per the previous comments.

**Comment by vasyugan** [comment]
> As, as per the previous comments.

So are you implying that currently, clickable notifications are not implemented? I thought I had seen such notifications in the past (recommending the installation of certain apps)

Well, if that's the case, there is probably nothing preventing you from embedding clickable links into the warning emails that the app sends out. Wouldn't this be doable with just a few lines of code? For me, this would make life quite a bit easier, if I could tell my users to just click the link in the mail.

**Comment by ChristophWurst** [comment]
@gdt the feature was implemented in 2021. Please submit new feature requests. Thanks.
