### ISSUE TITLE
Add icons for notifications

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/suspicious_login#212]
Currently the notifications do not have any icon. Would simply adding an icon via img/app.svg resolve this @nickvergessen?

The icon we want here is `icon-error`, that is: https://github.com/nextcloud/server/blob/master/core/img/actions/error.svg

(Otherwise for reference, @ChristophWurst mentioned the place the notifications are generated are at https://github.com/nextcloud/suspicious_login/blob/master/lib/Notifications/Notifier.php#L66-L73 )

**Comment by nickvergessen** [comment]
No, the notification app is not lurking into the content. You need to use setIcon in the prepare method

**Comment by szaimen** [comment]
example: https://github.com/nextcloud/firstrunwizard/pull/565/files
