### ISSUE TITLE
Can't download: curl timeout

### ISSUE THREAD

**Issue by wehkah** [nextcloud/suspicious_login#223]
Hello,

I'm trying to download this app, but this is the result:

`cURL error 28: Operation timed out after 30000 milliseconds with 452166 out of 1195120 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I think the reason for this is the restricted way the targeted machine is connected to the net. Is there any other way to download this app, maybe as a zip file?

Thanks in advance.

**Comment by ChristophWurst** [comment]
Hi,

can you download any other apps? The release tarballs of this apps are relatively small.

**Comment by rullzer** [comment]
You can just fetch it at https://github.com/nextcloud/suspicious_login/releases/download/v3.0.1/suspicious_login.tar.gz

From https://github.com/nextcloud/suspicious_login/releases
