### ISSUE TITLE
what does mean this graphic and where are the configuration option? 

### ISSUE THREAD

**Issue by boistordu** [nextcloud/suspicious_login#243]
![problem_nextcloud_suspiciousactivity_Annotation 2020-02-24 013645](https://user-images.githubusercontent.com/9523075/75123739-1f6ab900-56a2-11ea-9a15-c4cfdaa50c67.jpg)
I'm sorry but this is unclear to me. 
What's recall?
precision is mentionned between '()' so I guess that points to a possible definition. But how is the graphic made exactly? There are apparently no options to configure what's a suspicious activity and what a normal activity.
The x axis is clear, it's date. But what's the y axis? %? if yes then it is crazy that my external instance of this screenshot is classifying everything as suspicious....

**Comment by boistordu** [comment]
just FYI, the button in the sote : ask question doesn't work anymore.

**Comment by ChristophWurst** [comment]
You can find a good definition of recall and precision here: https://en.wikipedia.org/wiki/Precision_and_recall. It shows how many of the classified data sets are assigned to their expected class. So yes, it's a percentage.

And I think you're reading the results wrong. They are actually respectably good on your instance.

**Comment by ChristophWurst** [comment]
And as you can see in the readme the suspicious logins are *simulated* for the evaluation.

> There are apparently no options to configure what's a suspicious activity and what a normal activity.

No, because this app uses a neural net. There are no rules to define, but we let the system figure it out based on data from the instance.
