### ISSUE TITLE
How reset suspicious login data/model ?

### ISSUE THREAD

**Issue by davidv92** [nextcloud/suspicious_login#283]
Hello,

On my Nextcloud instance 'trusted_proxies' and 'forwarded_for_headers' wasn't properly configured, so the IP recorded by suspicious login was always the same, the local address of my reverse proxy, and suspicious login have been trained with these wrong data for a while...

Since I fixed the issue, most of login on the instance are detected as suspicious. 

Is there a way to reset the model and ignore all the data before a certain date ? Or more simply reset the application ? 

Thanks in advance for your support.

**Comment by ChristophWurst** [comment]
Check the tables `oc_login_address` and `oc_login_address_aggregated` and remove the incorrect entries.

**Comment by SimJoSt** [comment]
For anybody else finding this, the table `oc_login_address_aggregated` has since been renamed to `oc_login_ips_aggregated`.
