### ISSUE TITLE
Blocking Next cloud bookmark android app add bookmark API

### ISSUE THREAD

**Issue by dasbiswajit** [nextcloud/suspicious_login#286]
Hi There,
_**Suspicious Login**_ App is blocking Bookmark API call from the Android [app](https://play.google.com/store/apps/details?id=org.bisw.nxbookmarks&hl=en_GB). Below is the configuration:
- android 9 (EMUI9.1.0) 
- Device Huawei p20. 
- Nextcloudpi v1.24.0
- nextcloud 18.0.6
- Runnning in docker container on raspbian lite on Rasberry Pi 4 4GB.

The error is given below:

`{"reqId":"Xue@rz@O60kwebLtVEhNAwAAAAw","level":2,"time":"2020-06-15T18:32:16+00:00","remoteAddr":"192.168.1.1","user":"lukebeart","app":"suspicious_login","method":"GET","url":"/index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1","message":"Could not predict suspiciousness: No models found","userAgent":"Dalvik/2.1.0 (Linux; U; Android 9; EML-L09 Build/HUAWEIEML-L09)","version":"18.0.6.0"}`

I have checked for other devices its not blocking but some how raspbian lite on Rasberry Pi 4 4GB next cloud instance it is blocking that particular API call. Any reason you can find? App Code: [Repo](https://github.com/nextcloud/bookmarks) & Android App code: [Repo](https://gitlab.com/bisada/OCBookmarks). Create Bookmark API: [Docs](https://nextcloud-bookmarks.readthedocs.io/en/latest/bookmark.html#create-a-bookmark). I need to close this [issue](https://gitlab.com/bisada/OCBookmarks/-/issues/54). Any help will be appriciated.
Cheers
Biswajit.

**Comment by ChristophWurst** [comment]
This app is not even capable of blocking anything. The worst it can do is send the user a notification or email.

**Comment by dasbiswajit** [comment]
Thanks @ChristophWurst it was by two factor. Cheers. Biswajit
