### ISSUE TITLE
Time of login ?

### ISSUE THREAD

**Issue by Ajilis** [nextcloud/suspicious_login#340]
Is there a way to view the table of the suspicious login IP + Date + Time ?

**Comment by ChristophWurst** [comment]
yes: `login_address`.

**Comment by Ajilis** [comment]
Thanx christophe, but this can be shown on the webui of nextcloud ?

**Comment by ChristophWurst** [comment]
no, this is neither relevant to the user nor the admin

**Comment by Ajilis** [comment]
- So information of time login its only in database ?
- Does email information is send immediatly or one time in the day ?

**Comment by ChristophWurst** [comment]
This is not a support forum. Please use https://help.nextcloud.com/c/apps/suspiciouslogin/175 for your questions. Cheers.
