### ISSUE TITLE
View list of IPs

### ISSUE THREAD

**Issue by kicker334** [nextcloud/suspicious_login#351]
This may be a dumb question, but, how do you view a list of the IPs listed as suspicious or not suspicious from the app?

**Comment by ChristophWurst** [comment]
you don't. the suspiciousness is calculated on the fly and won't be persisted. you can only find a list of alerts in `oc_suspicious_login`

**Comment by kicker334** [comment]
where do I type that in at? Does the app block suspicious logins? Where does `oc_suspicious_login` get typed in at? Sorry for being new at this. 

Is the point of the app just to report suspiciousness not to do anything about it?

**Comment by ChristophWurst** [comment]
Please open a topic at https://help.nextcloud.com/c/apps/suspiciouslogin/175. The bug tracker isn't the right place to discuss those questions.

> Is the point of the app just to report suspiciousness not to do anything about it?

Yes.
