### ISSUE TITLE
Add PHP 8 compatibility

### ISSUE THREAD

**Issue by bargru** [nextcloud/suspicious_login#409]
The application is not compatible with PHP 8 and cannot be activated in the store:
`PHP with a version lower than 7.4 is required. `

Please add PHP 8 compatibility.

Note: The text is misleading. The application works with PHP 7.4 and not only with the lower version 7.3

**Comment by ChristophWurst** [comment]
https://help.nextcloud.com/t/testers-needed-for-v4-0-0-betas/106740

**Comment by ChristophWurst** [comment]
4.0.0 released
