### ISSUE TITLE
Can't enable the app

### ISSUE THREAD

**Issue by Mikeatme** [nextcloud/suspicious_login#425]
Hi Christoph,

I've got the same problem as described in #415. 
I tried to install the app on NC 21 with a version below 4.0 and ran into an error (`Error: There is no table with name 'xxx.oc_suspicious_login_model' in the schema.`)

After waiting for version 4.0 and trying to remove and/or reinstall now, it throws the same error. 
No difference between the browser-based installation or the cli-way with `occ`.

Do you have an idea how to fix this?

Kidn regards  
Michael

```
Error: Undefined index: settings at /var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404
/var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php - line 404:

OC\Log\ErrorHandler::onError(8, "Undefined index: settings", "/var/www/ht ... p", 404, { apps: [],r ... "})

/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php - line 143:

OC\AppFramework\Bootstrap\RegistrationContext->delegateContainerRegistrations([])

/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php - line 86:

OC\AppFramework\Bootstrap\Coordinator->registerApps([ "suspicious_login"])

/var/www/html/lib/private/Installer.php - line 146:

OC\AppFramework\Bootstrap\Coordinator->runLazyRegistration("suspicious_login")

/var/www/html/core/Command/App/Install.php - line 68:

OC\Installer->installApp("suspicious_login")

/var/www/html/3rdparty/symfony/console/Command/Command.php - line 255:

OC\Core\Command\App\Install->execute(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/html/3rdparty/symfony/console/Application.php - line 1009:

Symfony\Component\Console\Command\Command->run(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/html/3rdparty/symfony/console/Application.php - line 273:

Symfony\Component\Console\Application->doRunCommand(OC\Core\Command\App\Install {}, Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/html/3rdparty/symfony/console/Application.php - line 149:

Symfony\Component\Console\Application->doRun(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/html/lib/private/Console/Application.php - line 215:

Symfony\Component\Console\Application->run(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/html/console.php - line 100:

OC\Console\Application->run()

/var/www/html/occ - line 11:

require_once("/var/www/html/console.php")
```

**Comment by Mikeatme** [comment]
Raw Copy from the GUI

{"reqId":"kjUBpD2PEwtMaWixPtTf","level":3,"time":"2021-06-23T00:03:36+02:00","remoteAddr":"88.133.186.151","user":"XXX.YYY","app":"settings","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Doctrine\\DBAL\\Schema\\SchemaException","Message":"There is no table with name 'nextcloud.oc_suspicious_login_model' in the schema.","Code":10,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Schema/Schema.php","line":180,"function":"tableDoesNotExist","class":"Doctrine\\DBAL\\Schema\\SchemaException","type":"::","args":["nextcloud.oc_suspicious_login_model"]},{"file":"/var/www/html/lib/private/DB/SchemaWrapper.php","line":89,"function":"getTable","class":"Doctrine\\DBAL\\Schema\\Schema","type":"->","args":["nextcloud.oc_suspicious_login_model"]},{"file":"/var/www/html/custom_apps/suspicious_login/lib/Migration/Version0Date20181214103754.php","line":46,"function":"getTable","class":"OC\\DB\\SchemaWrapper","type":"->","args":["suspicious_login_model"]},{"file":"/var/www/html/lib/private/DB/MigrationService.php","line":455,"function":"changeSchema","class":"OCA\\SuspiciousLogin\\Migration\\Version0Date20181214103754","type":"->","args":[{"__class__":"OC\\Migration\\SimpleOutput"},{"__class__":"Closure"},{"tablePrefix":"oc_"}]},{"file":"/var/www/html/lib/private/DB/MigrationService.php","line":418,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"/var/www/html/lib/private/Installer.php","line":163,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":["latest",true]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->","args":["suspicious_login"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["suspicious_login"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Schema/SchemaException.php","Line":35,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36","version":"21.0.0.18","id":"60d25e416b119"}

**Comment by ChristophWurst** [comment]
The migration https://github.com/nextcloud/suspicious_login/blob/master/lib/Migration/Version0Date20181214103754.php fails.

However, I do not see a possible path where the migration would be run but the table `oc_suspicious_login_model` doesn't exist.

If you interfere with the schema manually then migrations will fail. They expect preceding migrations to have been run.
