### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/suspicious_login#44]
Right now the classifier only support IPv4. For IPv6 we'll probably need a second classifier as the structure (and thus bit vector size) is different.

**Comment by nicokaiser** [comment]
Shouldn't the plugin just ignore IPv6 logins then? All my logins (from IPv6 addresses) are considered suspicious, which may be a problem in countries where IPv6 slowly becomes widely adopted (Austria)...

**Comment by ChristophWurst** [comment]
Yeah, basically the code just refers to this ticket https://github.com/nextcloud/suspicious_login/blob/014edd708581efb55b20edf1149e0b795b2728d2/lib/Service/LoginClassifier.php#L110 :wink: 

The consideration was: rather warn more frequently (you usually don't login often) than allowing attackers to bypass this app's classification.

**Comment by nicokaiser** [comment]
Absolutely right! Thanks for the great work, by the way!

**Comment by Gatak** [comment]
Would specifying local prefixes be a good thing? At least here, I have several /64 prefixes and my clients use temporary addresses, which means the bottom part of the IP changes over time. It means 2^64 possible addresses. They would fill upp the db quite quickly, at least on systems with many clients.

Here in Sweden we also have IPv6 on the mobile networks, How should a classifyer deal with those prefixes?

**Comment by ChristophWurst** [comment]
I have not considered this yet but will have a closer look when I start the implementation of the ipv6 classifier. For the classifier itself it shouldn't be much of a problem to have much data, unless it's getting ridiculously big. Could you tell me the rough number of users on your instances and number of rows in `oc_login_address` and `oc_login_address_aggregated`?

**Comment by Gatak** [comment]
I'll look when I'm back home in a few days.

**Comment by Gatak** [comment]
@ChristophWurst 

**`oc_login_address`**
- 12 entries. 
- Only IPv4 LAN addresses (192.xxx)
- no public IP's or IPv6 addresses. 

**`oc_login_address_aggregated`** 
- 176 rows.
- 82 IPv4 addresses (including public IP's).
-- Public IP's seen 307 times
-- LAN IP's seen ~60000 times
- 94 IPv6 addresses
-- 7 different /48 prefixes which includes 15 different /64 prefixes. 
-- Seen 732 times.

3 users only. This is a home server.

**Comment by Gatak** [comment]
Oh, and I also noticed this in the log-file:
> Login is not from IPv4, hence it's considered suspicious

**Comment by ChristophWurst** [comment]
Good news: I've started working on the ipv6 support and the results are looking promising

```
$ php ../../occ suspiciouslogin:train --v6 -e 30 --now=1561111200 --max-age=50
Prescision(y): 0.99923722349352
Prescision(n): 0.976
Recall(y): 0.97542814594192
Recall(n): 0.99925539836188
```

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/suspicious_login/pull/107. There is still a lot to do, but I'll try to finish this in the next few weeks.

**Comment by ChristophWurst** [comment]
Btw @Gatak thanks for the tip with the more and less significant parts of the v6 addresses. I'm not using the most significant 32 bits and my available test data set confirms that the rest is not relevant and changes very often.
