### ISSUE TITLE
Running ./occ Suspiciouslogin:optimize fails with call to undefined function pcntl_signal_dispath

### ISSUE THREAD

**Issue by pzzszk** [nextcloud/suspicious_login#602]
NC 23.0.0 with Suspiciouslogin Version 4.1.0 generates an error when running the ./occ Suspiciouslogin:optimize command in batch.  It fails with a call to an undefined function pcntl_signal_dispatch.

This command has worked in previous NC & Suspiciouslogin app versions.

Log Output:
Optimizing a MLP trainer in 100 steps

Epoch 0: epochs= 330 layers= 2 shuffledRate=0.005 randomRate=2.000, learningRate=0.0070
  Step width for next config neighbor: 0.8
An unhandled exception has been thrown:
Error: Call to undefined function pcntl_signal_dispatch() in /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/Loop/NativeDriver.php:161
Stack trace:
#0 /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#1 /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#2 /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#3 /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/functions.php(229): Amp\Loop::run()
#4 /var/www/nextcloud/apps/suspicious_login/lib/Service/MLP/OptimizerService.php(204): Amp\Promise\wait()
#5 /var/www/nextcloud/apps/suspicious_login/lib/Command/Optimize.php(81): OCA\SuspiciousLogin\Service\MLP\OptimizerService->optimize()
#6 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\SuspiciousLogin\Command\Optimize->execute()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#8 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#10 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#11 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#12 /var/www/nextcloud/occ(11): require_once('...')
#13 {main}

Next Error: Loop exceptionally stopped without resolving the promise in /var/www/nextcloud/apps/suspicious_login/vendor/amphp/amp/lib/functions.php:231
Stack trace:
#0 /var/www/nextcloud/apps/suspicious_login/lib/Service/MLP/OptimizerService.php(204): Amp\Promise\wait()
#1 /var/www/nextcloud/apps/suspicious_login/lib/Command/Optimize.php(81): OCA\SuspiciousLogin\Service\MLP\OptimizerService->optimize()
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\SuspiciousLogin\Command\Optimize->execute()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('...')

**Comment by ChristophWurst** [comment]
is the function disabled via php.ini? on https://www.php.net/manual/en/function.pcntl-signal-dispatch.php I don#t see any indication that it would need an optional php module, this function *should* be included in the default distribution of php.

**Comment by pzzszk** [comment]
Well spotted !!!  2 years ago - I had disabled some of the functions in order to harden PHP.  Clearly too hard.  All is good now that I have removed the disabled list.  Thanks.
