### ISSUE TITLE
Update app to support NC v24

### ISSUE THREAD

**Issue by bcutter** [nextcloud/suspicious_login#643]
Please make it compatible with NC v24.

**Comment by sunjam** [comment]
Are you able to manually enable the app and get it working as-is?

**Comment by bcutter** [comment]
It runs on NC 24, yes.

**Comment by nunesgh** [comment]
It would be great to see an upgrade path through the web interface, though.

**Comment by bcutter** [comment]
> Are you able to manually enable the app and get it working as-is?

To specify my answer: hacking the appinfo (max-version) and enabling the app afterwards works.

Without the notice of any other changes of NC core which might affect the function of this app it might be sufficient, to simply do the same and push that as new app release "NC 24 compatibility".

**Comment by stephang** [comment]
I guess 83dbe35deccbf17fe20b66c026b39b19d125900b is related and will fix this issue?

@nickvergessen

**Comment by nickvergessen** [comment]
I'm not in charge of this app, so no idea.
As you can see in https://github.com/nextcloud/server/issues/31982 I'm just a script executor on these PRs.

**Comment by ChristophWurst** [comment]
the next release will support up to nextcloud 25 and php8.1
