### ISSUE TITLE
First (legitimate) login attempt always fails (silently)

### ISSUE THREAD

**Issue by bcutter** [nextcloud/suspicious_login#645]
Since having the suspicious login app enabled, every first of my own login attempts fails (of course with correct authentication data), meaning the 2FA page is not loading. Login page simply reloads, without any message. Second attempt always works.

Nothing in logs.

- How to debug this?
- How can I check/monitor what exactly happens when the 1st login attempt fails/is rejected?

**Comment by marcelklehr** [comment]
Can you verify that this is indeed due to the suspicious_login app?

**Comment by bcutter** [comment]
I think it's the bruteforce (app?):

Almost on EVERY first login attempt it just fails silently, on the 2nd one it succeeds.
NC-LOG: `Bruteforce attempt from "xxx.xxx.xxx.xxx" detected for action "login".`

...even that IP address space is explicitly whitelisted.

**Comment by joshtrichards** [comment]
> Maybe by just disabling suspicious_login app and trying to login?

Yes, that's how I'd suggest testing it.

**Comment by bcutter** [comment]
I tested it few times in the last days, even tried to provoke it in the last hours on different endpoints (Windows, iOS) with different browsers. App enabled. Strangely it did not happen a single time.

Running NC v27.1.5.1 with Suspicious Login v5.0.0.

Maybe something in NC server fixed this issue? Maybe time to monitor this for a while.

**Comment by joshtrichards** [comment]
`suspicious_logins` merely registers with Server to get notified about login attempts. It never gets involved in authentication outside of being a passive listener.

I can't think of any way it would prevent logging in - short of crashing Nextcloud outright (which would surely be logged).

I agree the problem seems elsewhere - BFP of otherwise.

**Comment by joshtrichards** [comment]
I'm going to close this one out here, but if the behavior returns and there are indications it's related specifically to the `suspicious_logins` app we can always revisit.
