### ISSUE TITLE
Misleading german translation in machine learning chart legend

### ISSUE THREAD

**Issue by z0rgster** [nextcloud/suspicious_login#676]
Hi,

in the german translation the chart legend of the training statistics labels the data rows as "Präzision" and "Widerruf". I was wondering quite some time what the "Widerruf" part should mean and didn't really understand the chart beacuse of this. Today I realized that the machine learning terms "precision" and "recall" are meant and now everything makes sense.

The word "recall" has a double meaning: As a verb it roughly means "to remember" and as a noun it describes the action of "revoking something" as in a "product recall". For the german translation the latter meaning was translated to "Widerruf".

The proper german terms of "precision" and "recall" in the context of machine learning are "Genauigkeit" and "Trefferquote" [(source)](https://de.wikipedia.org/wiki/Beurteilung_eines_bin%C3%A4ren_Klassifikators#Genauigkeit-Trefferquote-Diagramm).

While writing this issue, I noticed that I can make translation suggestions on Transifex (and did just that). The translation of "precision" was already updated from "Präzision" to "Genauigkeit" and applied to the description text above the chart. However, the chart legend itself was not updated, which is the reason why I am still opening this issue. The strings of the chart legend might not be connected to the translation framework yet.

**Comment by ChristophWurst** [comment]
Our translations are handled on https://www.transifex.com/nextcloud/. You can also check in with translators at https://help.nextcloud.com/c/translations/23.

**Comment by z0rgster** [comment]
Please note my last paragraph. The translation for "precision" was changed two years ago to "Genauigkeit" on Transifex but the chart still uses "Präzision" to this day. That seems to be a code problem, not a translation problem.

**Comment by ChristophWurst** [comment]
The translation files at https://github.com/nextcloud/suspicious_login/blob/master/l10n/de.js say Präzision.

The nightly Transifex job is also still running: https://github.com/nextcloud/suspicious_login/commits/master

Was this possible fixed for the wrong variant of the German translation? e.g. de vs de_De or similar? Best ask in the forums, our translators are more familiar with these problems.

**Comment by z0rgster** [comment]
Alright, that might be it. I just looked at de_De. Thank you!
