### ISSUE TITLE
Drop support for PHP 7.4

### ISSUE THREAD

**Issue by st3iny** [nextcloud/suspicious_login#807]
- [ ] Adjust `info.xml`
- [ ] Adjust `composer.json`
- [ ] Adjust workflows (if necessary)

**Comment by joshtrichards** [comment]
I'm a little confused about this one because this looks like it was basically done before the Issue was created:

#703
#758 

Is there anything still left to do here that I'm missing?

**Comment by st3iny** [comment]
Yeah, I don't know either.
