### ISSUE TITLE
0 rows on login_address table

### ISSUE THREAD

**Issue by renellis** [nextcloud/suspicious_login#825]
Hello,

I would like to see the list of login attempts on my instance.

On the admin page, I can see: **367008 logins (including client connections), of which 31 are distinct (IP, UID) tuples.**

However, when I check the login_address table on the Nextcloud database, it seems to be empty:

nextcloud_test=> SELECT * FROM pg_login_address ;
 id | uid | ip | created_at
----+-----+----+------------
(0 rows)

Am I'm looking on the wrong place?

**Comment by ChristophWurst** [comment]
look into the aggregated table

please use https://help.nextcloud.com/ for support
