### ISSUE TITLE
Version on app store and compatible versions

### ISSUE THREAD

**Issue by tflidd** [nextcloud/suspicious_login#827]
If I go on the app store, the latest version is 4.2.1 and no version beyond NC25 is supported.
https://apps.nextcloud.com/apps/suspicious_login

I was surprised that people with newer versions were using this app. And instead of releases, there are tagged versions that are more recent. From the app store however, it looks like an abandoned app. If I go on the app within a NC setup, I can find a version 4.4.0.

It would be great to clarify. I often use the app store to search for functions people are asking, and for apps like this I say, sorry, we had something in the past but it is not supported any more.

**Comment by ChristophWurst** [comment]
The app is shipped: https://github.com/nextcloud/suspicious_login/pull/828
