### ISSUE TITLE
Huge database table due to login attempts/reconnects from Thunderbird client CalDAV

### ISSUE THREAD

**Issue by Tha14** [nextcloud/suspicious_login#859]
I've got a few alerts of my nextcloud server's database becoming extremely large all of a sudden a few days ago. I am currently using nextcloud 27.1.7 and Suspicious Login 5.0.0. If I shut down thunderbird the entries in the table `oc_login_address` stop increasing(this is a bug with the thunderbird version I am using as far as I understand). I believe that there should be a value a value set to not allow the database to hold more than a specific amount of entries.

![image](https://github.com/nextcloud/suspicious_login/assets/5931740/ab696fef-79bd-456a-bb18-b8196072b389)

**Comment by ChristophWurst** [comment]
oc_login_address is for temporary storage. the data is compressed and transformed into oc_login_ips_aggregated in a background job. Make sure it runs reliably.

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html

I also recommend connecting Thunderbird with an app password, not the login password.
