### ISSUE TITLE
postgres errors during cronjob

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/suspicious_login#89]
I noticed in my nextcloud log that an error is happening during the cronjob. It is happening because at some point the query `INSERT INTO "oc_login_address_aggregated" ("uid", "ip", "seen", "first_seen", "last_seen") VALUES($1, $2, $3, $4, $5)` tries to insert a duplicate value for `(uid, ip)` which violates a unique key defined on that table.
Am running nextcloud 16.0.1 on a linux server with nginx and postgres 10.8.
```
Error	core	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "seen", "first_seen", "last_seen" FROM "oc_login_address_aggregated" WHERE ("uid" = ?) AND ("ip" = ?)' with params ["***redacted***", "***redacted***"]: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 184:

    Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exceptio ... k", Doctrine\DBA ... ]})

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 158:

    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "An exceptio ... k")

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 938:

    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "SELECT \"se ... )", { 1: "***redacted*** ... "})

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

Cased by Doctrine\DBAL\Driver\PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 930:

    Doctrine\DBAL\Driver\PDOStatement->execute()

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

Cased by PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php - line 141:

    PDOStatement->execute(null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 930:

    Doctrine\DBAL\Driver\PDOStatement->execute()

    /var/www/nextcloud/lib/private/DB/Connection.php - line 195:

    Doctrine\DBAL\Connection->executeQuery("SELECT \"se ... )", [ "***redacted*** ... "], [ 2,2], null)

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 219:

    OC\DB\Connection->executeQuery("SELECT \"se ... )", { uid: "***redacted*** ... "}, [])

    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214:

    Doctrine\DBAL\Query\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/Service/ETLService.php - line 134:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/nextcloud/apps/suspicious_login/lib/BackgroundJob/ETLJob.php - line 51:

    OCA\SuspiciousLogin\Service\ETLService->extractAndTransform()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 77:

    OCA\SuspiciousLogin\BackgroundJob\ETLJob->run(null)

    /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 59:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 123:

    OCP\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

**Comment by ChristophWurst** [comment]
Apparently the wrong error is thrown on Postgres. This DB exception is actually expected and handled: https://github.com/nextcloud/suspicious_login/blob/e9fef6a653148e93619a097195a27dd860bdd67e/lib/Service/ETLService.php#L128-L130

**Comment by jknockaert** [comment]
Could it be that the issue is more with the transaction being rolled back than with unique key violation?

**Comment by ChristophWurst** [comment]
I took a bit of a closer look and what I was referring to is indeed incorrect. The stack trace points to https://github.com/nextcloud/suspicious_login/blob/e9fef6a653148e93619a097195a27dd860bdd67e/lib/Service/ETLService.php#L134, which means the duplicate is already detected.

> Could it be that the issue is more with the transaction being rolled back than with unique key violation?

You are right in that the code is run in an transaction. The unhandled exception causes a rollback. However, I do not think this is the root of the problem here.

**Comment by jknockaert** [comment]
> > Could it be that the issue is more with the transaction being rolled back than with unique key violation?
> 
> You are right in that the code is run in an transaction. The unhandled exception causes a rollback. However, I do not think this is the root of the problem here.

I was thinking that perhaps the exception to be handled at the php level may be an aborted transaction rather than a unique key violation.

**Comment by ChristophWurst** [comment]
You're right. The problem is that postgres does not allow us to continue the transaction after the error. I have to to restructure the code for this.

**Comment by adi-dev** [comment]
Hi guys, don't want to be annoying, but any progress on this, there were few version upgrades but I still have this error on my home server. Cheers.

**Comment by ChristophWurst** [comment]
Hi, no, not really. But if you're interested in doing a little coding and refactoring exercise please let me know :v:

**Comment by adi-dev** [comment]
I haven't analysed the code yet, if you could save me some time and point in the right direction, I can have a try as I do, in 15% of my work, PHP and PGSQL 😄 I'll more than happy to help

**Comment by ChristophWurst** [comment]
What we do (in pseudo code)

```
try {
    insert()
} catch (…) {
    select()
    if (nothing found) {
        // ignore
    }
    update()
}
```

What we should do
```
select()
if (nothing found) {
    insert()
} else {
    update()
}
```

**Comment by gruentee** [comment]
Hi there, same setup – same error here. I'd be glad if it could be solved :+1:

**Comment by ChristophWurst** [comment]
> Hi there, same setup – same error here. I'd be glad if it could be solved +1

Just add your :+1: to the original report. Then we know more people are affected. But please don't do these comments. Thanks :v:

**Comment by adi-dev** [comment]
@ChristophWurst I have modified the script locally for testing. So far there are no entries in `oc_login_address`, `oc_login_address_aggregated`, `oc_suspicious_login` nor `oc_suspicious_login_model`, if these are the tables I'm looking for. Can I trigger ETLService manually, is it `php -f occ suspiciouslogin:etl`?

**Comment by adi-dev** [comment]
There is pull request #166 It cleared the errors in the log, but still doesn't create any entries in `login_address_aggregated` table.

**Comment by adi-dev** [comment]
@ChristophWurst please ignore my last pull request as I found it didn't populate `login_address_aggregated` with any data. For some reason `fetch()` didn't return any data but `is_null($existing)` was always `false`. This time using `fetchAll()` and `sizeof($existing) == 0` to detect if the record is in the table. So far it works fine and I have some data populating in the table. New pull request is #168 please review and try.

**Comment by gruentee** [comment]
> > Hi there, same setup – same error here. I'd be glad if it could be solved +1
> 
> Just add your  to the original report. Then we know more people are affected. But please don't do these comments. Thanks

Allright, didn't know that was the policy here.
