### ISSUE TITLE
Rephrase info, so that user knows that IP address is sent to 3rd party website

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/suspicious_login#891]
https://github.com/nextcloud/suspicious_login/commit/bbd630915d36317a9c0bb2347ea7ad639776c6ca#diff-224ccb62b5756482500f03a0e761ed947209c14d1b59aad9025d8bcfb5bb379bR91

> You can get more info by pressing the button which will open %s and show info about the suspicious IP-address

**Comment by kyteinsky** [comment]
To add to this, please keep it disabled by default and add an option to change the lookup website.
Please let me know if this needs a new issue.

**Comment by ChristophWurst** [comment]
> To add to this, please keep it disabled by default and add an option to change the lookup website.

This was discussed in https://github.com/nextcloud/suspicious_login/issues/209.

**Comment by ChristophWurst** [comment]
@jancborchardt do you have in idea for a simple yet clear phraze we could use?

**Comment by jancborchardt** [comment]
> More info about the suspicious IP address available on iplookup.flagfox.net

And then the button saying: "Open iplookup.flagfox.net"

**Comment by kyteinsky** [comment]
> This was discussed in #209.

sounds reasonable. Maybe in the long-term it can have a setting for the url in the form of a string template `https://iplookup.flagfox.net/?ip=$ip`? Or maybe not.

Rephrasing the text is a good compromise.
